# SPDX-FileCopyrightText: 2016-2020 CloudCannon <support@cloudcannon.com>
# SPDX-FileCopyrightText: 2022 Sidings Media <packetblade@sidingsmedia.com>
# SPDX-License-Identifier: MIT

# ----
# Site

title: Packet Blade
url: "https://packetblade.sidingsmedia.com"
baseurl: ""
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: /images/rendered/packet-1920x1496.png
description: Packet Blade - A high density low cost network appliance
author:
  name: Sidings Media
  email: packetblade@sidingsmedia.com
  twitter: sidingsmedia
social:
  name: Sidings Media
  links:
    - https://github.com/PacketBlade/
locale: en_GB

# -----
# Build

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 1500
          height: 2500
  - scope:
      path: ""
    values:
      layout: "page"
  - scope:
      path: "index.html"
    values:
      layout: "default"
  - scope:
      path: "contact.html"
    values:
      full_width: true

jekyll-archives:
  enabled:
    - categories

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  social_icons:
    - Facebook
    - Instagram
    - LinkedIn
    - Pinterest
    - Tumblr
    - Twitter
    - YouTube
    - RSS
